name: Test deploy                    # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - main                        
jobs:                                # Job 설정
  build:
    name: react build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v4.1.1
      
      - name: Check Node v            # Node v 확인
        run: node -v
        
      - name: Install dependencies    # 의존 파일 설치
        run: npm install

      - name: Install react-router-dom
        run: npm add react-router-dom

      - name: Install @chakra-ui/react
        run: npm add @chakra-ui/react
       
      - name: Install react-icons/fa
        run: npm add react-icons/fa
      
      - name: Generate react build    # React Build
        run: npm run build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.MY_SECRET_KEY}}
          publish_dir: ./src