name: Build and Deploy # Github Action 이름

on:
  push:
    branches:
      - main # 빌드할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "20.12.2"
        
      - name: Install dependencies
        run: yarn install

      - name: Install react-router-dom
        run: yarn add react-router-dom

      - name: Install @chakra-ui/react
        run: yarn add @chakra-ui/react

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run build # 빌드 스크립트

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.MY_SECRET_KEY }}
          publish_dir: ./build # 이 폴더에 있는 파일을 배포